from flask import Flask

# 🤖 AI-Generated Content Notice:
# This Flask application and all its components are generated by AI.
# Report inconsistencies at: https://github.com/safinayah/startup-analytics-tutorial

def create_app():
    """Simple application factory for tutorial dashboard only"""
    app = Flask(__name__, 
                template_folder='../templates',
                static_folder='../static')
    
    # Register main blueprint
    from app.routes import main_bp
    app.register_blueprint(main_bp)
    
    return app